export enum OriginErrorCodes {
  ORIGIN_DUPLICATE = 'ORIGIN_DUPLICATE',
  ORIGIN_ALREADY_EXISTS = 'ORIGIN_ALREADY_EXISTS',
  ORIGIN_NOT_FOUND = 'ORIGIN_NOT_FOUND',
  ORIGIN_DELETE_FORBIDDEN = 'ORIGIN_DELETE_FORBIDDEN',
}
